In [8]:
#Required imports
import numpy as np
import random
import gym
import time
from IPython.display import clear_output

In [9]:
env = gym.make("FrozenLake-v0")

In [10]:
#initialize action and state spaces
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

In [11]:
#initialize Q-table
q_table = np.zeros([state_space_size,action_space_size])
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
#Initializing Q-Learning Parameters
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [13]:
rewards_all_episodes = []

In [14]:
#Q-learning algorithm
for episode in range(num_episodes):
    #initialize new episode params
    state = env.reset()
    done = False
    
#     #####useless visualization#####
#     print("******EPISODE{}******\n\n\n\n".format(episode+1))
#     time.sleep(1)
#     ######end of useless visualization#####
    
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
#         #####useless visualization#####
#         clear_output(wait = True)
#         env.render()
#         time.sleep(0.3)
#         ######end of useless visualization#####
        
        
        #Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
        
        #Take new action    
        new_state, reward, done, info = env.step(action)
        
        #Update Q-table
        q_table[state,action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]))
            
        #Set new state
        state = new_state
        
        #Add new reward
        rewards_current_episode += reward 
        
        if done:
            
#             #####useless visualization#####
#             clear_output(wait=True)
#             env.render()
#             if reward == 1:
#                 print("****You reached the goal!****")
#                 time.sleep(3)
#             else:
#                 print("****You fell through a hole!****")
#                 time.sleep(3)
#                 clear_output(wait=True)
#             ######end of useless visualization#####
                
            break
    
    #Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * \
        np.exp(-exploration_decay_rate*episode)
    
    #Add current episode reward to total rewards list
    rewards_all_episodes.append(rewards_current_episode)

In [15]:
#Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = \
    np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000


for r in rewards_per_thousand_episodes:
    print("{}: {}".format(count, str(sum(r/1000))))
    count += 1000
    







1000: 0.04900000000000004
2000: 0.19700000000000015
3000: 0.43800000000000033
4000: 0.5520000000000004
5000: 0.6180000000000004
6000: 0.6610000000000005
7000: 0.6410000000000005
8000: 0.6880000000000005
9000: 0.6690000000000005
10000: 0.7160000000000005


In [16]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)




********Q-table********

[[0.58405569 0.5407144  0.53886036 0.52782966]
 [0.25947223 0.32145305 0.2727128  0.52956587]
 [0.39832211 0.40389772 0.41560835 0.47970348]
 [0.24525728 0.28185711 0.29816697 0.46217652]
 [0.6071876  0.39496111 0.30789163 0.42759897]
 [0.         0.         0.         0.        ]
 [0.18441499 0.16812672 0.37889649 0.09263664]
 [0.         0.         0.         0.        ]
 [0.34040837 0.41593509 0.48177029 0.65482966]
 [0.34729415 0.68498514 0.56617136 0.41326305]
 [0.69002027 0.36930359 0.41873134 0.43528723]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.5688481  0.44413111 0.77668172 0.53146997]
 [0.74621249 0.86406698 0.76268939 0.69060571]
 [0.         0.         0.         0.        ]]
