In [2]:
import numpy as np
import random
import gym
import time
from IPython.display import clear_output

In [3]:
env = gym.make("FrozenLake-v0")

In [6]:
#initialize action and state spaces
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

In [9]:
#initialize Q-table
q_table = np.zeros([state_space_size,action_space_size])
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
#Initializing Q-Learning Parameters
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [15]:
rewards_all_episodes = []

In [19]:
#Q-learning algorithm
for episode in range(num_episodes):
    #initialize new episode params
    state = env.reset()
    done = False
    
    #####useless visualization#####
    print("******EPISODE{}******\n\n\n\n".format(episode+1))
    time.sleep(1)
    ######end of useless visualization#####
    
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        #####useless visualization#####
        clear_output(wait = True)
        env.render()
        time.sleep(0.3)
        ######end of useless visualization#####
        
        
        #Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
        
        #Take new action    
        new_state, reward, done, info = env.step(action)
        
        #Update Q-table
        q_table[state,action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]))
            
        #Set new state
        state = new_state
        
        #Add new reward
        rewards_current_episode += reward 
        
        if done:
            
            #####useless visualization#####
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
            ######end of useless visualization#####
                
            break
    
    #Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * \
        np.exp(-exploration_decay_rate*episode)
    
    #Add current episode reward to total rewards list
    rewards_all_episodes.append(rewards_current_episode)

  (Up)
SFFF
FHFH
FFFH
HFFG


KeyboardInterrupt: 

In [17]:
#Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = \
    np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000


for r in rewards_per_thousand_episodes:
    print("{}: {}".format(count, str(sum(r/1000))))
    count += 1000
    







1000: 0.04900000000000004
2000: 0.18000000000000013
3000: 0.3930000000000003
4000: 0.5570000000000004
5000: 0.6530000000000005
6000: 0.6460000000000005
7000: 0.7040000000000005
8000: 0.6850000000000005
9000: 0.6620000000000005
10000: 0.6910000000000005
11000: 0.6790000000000005
12000: 0.7030000000000005
13000: 0.6690000000000005
14000: 0.6990000000000005
15000: 0.7000000000000005
16000: 0.6860000000000005
17000: 0.6830000000000005
18000: 0.6750000000000005
19000: 0.6920000000000005
20000: 0.6870000000000005
21000: 0.6850000000000005
22000: 0.6840000000000005
23000: 0.6880000000000005
24000: 0.6870000000000005
25000: 0.7070000000000005
26000: 0.6780000000000005
27000: 0.6940000000000005
28000: 0.6710000000000005
29000: 0.6940000000000005
30000: 0.6900000000000005
31000: 0.6700000000000005
32000: 0.6960000000000005
33000: 0.6960000000000005
34000: 0.7240000000000005
35000: 0.6870000000000005
36000: 0.6650000000000005
37000: 0.6980000000000005
38000: 0.6930000000000005
39000: 0.6990000000

In [18]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)




********Q-table********

[[0.48989934 0.48878679 0.48766029 0.48966302]
 [0.41144536 0.31400807 0.30505188 0.47154542]
 [0.43582852 0.39208127 0.42404123 0.45486882]
 [0.25077437 0.41810116 0.28725133 0.44851562]
 [0.49626898 0.43656853 0.32765843 0.31247636]
 [0.         0.         0.         0.        ]
 [0.26078894 0.1407835  0.19166344 0.13832385]
 [0.         0.         0.         0.        ]
 [0.40086976 0.43577989 0.50388273 0.5223007 ]
 [0.41133206 0.55164089 0.52554229 0.31828891]
 [0.47185062 0.42668242 0.4342857  0.41866389]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.61975422 0.47102948 0.65197119 0.55364279]
 [0.69019658 0.82427233 0.74177968 0.69895371]
 [0.         0.         0.         0.        ]]
